upstream backends {
    server 10.7.27.219:3001 max_fails=1 fail_timeout=10s;   # Backend A (Laptop 1)
    server 10.7.5.228:3002  max_fails=1 fail_timeout=10s;   # Backend B (Laptop 2)
}

# Port 80: redirect all plain HTTP to HTTPS
server {
    listen 80;
    server_name app.teamX.test api.teamX.test;
    return 301 https://$host$request_uri;
}

# Port 443: TLS terminates here
server {
    listen 443 ssl;
    http2 on;
    server_name app.teamX.test api.teamX.test;

    ssl_certificate     /opt/homebrew/etc/nginx/certs/app.teamX.test.crt;
    ssl_certificate_key /opt/homebrew/etc/nginx/certs/app.teamX.test.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://backends;      # plain HTTP to backends (TLS ends at nginx)

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_connect_timeout 2s;
        proxy_next_upstream error timeout http_502;

        add_header X-Upstream $upstream_addr always;
    }
}
